#!/usr/bin/env bash
SCRIPTPATH=$(dirname $(readlink -f "$0"))

mkdir -p $HOME/.config/nvim/plugin
mkdir -p $HOME/.config/nvim/after/plugin
mkdir -p $HOME/.config/nvim/lua/kelvin
mkdir -p $HOME/.config/nvim/autoload

# link wholesale
for f in `find "$(pwd)" -regex ".*\.vim$\|.*\.lua$" | sed "s|^\./||"`; do
    localfp=${f#"$SCRIPTPATH"}
    rm -rf ~/.config/nvim$localfp
    ln -s $f $HOME/.config/nvim$localfp
done

if [ ! -f "$HOME/.local/share/nvim/site/autoload/plug.vim" ]; then
    sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
           https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
fi

ln -sf $SCRIPTPATH/coc-settings.json ~/.config/nvim/coc-settings.json
